services:
  # Servicio para MongoDB
  mongodb:
    image: mongo:latest   # Usaremos la imagen oficial de MongoDB
    container_name: mongodb_container
    ports:
      - "27017:27017"     # Mapeamos el puerto 27017 del contenedor al puerto 27017 de la máquina local
    volumes:
      - mongo_data:/data/db  # Persistimos los datos en un volumen para que no se pierdan al reiniciar el contenedor
    networks:
      - app_network

  # Servicio para la aplicación Express
  app:
    build: .
    container_name: express_app
    ports:
      - "3001:3001"    # Mapeamos el puerto 3000 del contenedor al puerto 3000 de la máquina local
    depends_on:
      - mongodb       # Aseguramos que el contenedor de MongoDB se inicie primero
    networks:
      - app_network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase # URL de conexión a MongoDB en el contenedor
    volumes:
      - .:/usr/src/app  # Para montar tu aplicación local en el contenedor de Express

volumes:
  mongo_data:   # Volumen para persistir los datos de MongoDB
    driver: local

networks:
  app_network:
    driver: bridge
